apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-chaos
  namespace: litmus-demo
spec:
  appinfo:
    appns: 'litmus-demo'
    applabel: 'app=nginx-target'
    appkind: 'deployment'
  engineState: 'active'
  chaosServiceAccount: pod-delete-sa
  jobCleanUpPolicy: 'delete'
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '20'
            - name: CHAOS_INTERVAL
              value: '10'
            - name: FORCE
              value: 'false'
            - name: PODS_AFFECTED_PERC
              value: '50'
